version: '3'
services:
  cs-generator:
    image: "cs-generator:latest"
    container_name: "cs-generator"
    build:
      context: .
      dockerfile: CSharpGenerator.Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "8081:80"
  identity-server:
    image: "auth-service:latest"
    container_name: "auth-service"
    build:
      context: .
      dockerfile: IdentityServer.Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "80:80"
    links:
    - db:database
  web:
    image: "template-service:latest"
    container_name: "template-service"
    build:
      context: .
      dockerfile: WebApi.Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "8080:80"
    links:
    - db:database
    - identity-server:identity-server
    - cs-generator:cs-generator
  db:
    image: "database-service:latest"
    container_name: "database-service"
    build:
      context: .
      dockerfile: Couchbase.Dockerfile
    ports:
    - "8091:8091"