version: '3'
services:
  web:
    image: "template-service:latest"
    container_name: "template-service"
    build: .
    ports:
    - "8080:80"
    links:
    - db:database
  db:
    image: couchbase
    ports:
    - "8091:8091"