name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build csharp-generator
      run: docker build . --file ./docker/Release/CSharpGenerator.Dockerfile --tag ts-csharp-generator:$(date +%s)
